#!/bin/bash
#
# Print banner art.

#######################################
# Print a board. 
# Globals:
#   BG_BROWN
#   NC
#   WHITE
#   CYAN_LIGHT
#   RED
#   GREEN
#   YELLOW
# Arguments:
#   None
#######################################
print_banner() {

  clear

  printf "\n\n"

  printf "${GREEN}";
  printf "MAIKYSOFT MAIKYSOFT MAIKYSOFT MAIKYSOFT MAIKYSOFT MAIKYSOFT MAIKYSOFT MAIKYSOFT MAIKYSOFT \n";
  printf "MAIKYSOFT MAIKYSOFT MAIKYSOFT MAIKYSOFT MAIKYSOFT MAIKYSOFT MAIKYSOFT MAIKYSOFT MAIKYSOFT  \n";
  printf "MAIKYSOFT MAIKYSOFT MAIKYSOFT MAIKYSOFT MAIKYSOFT MAIKYSOFT MAIKYSOFT MAIKYSOFT MAIKYSOFT  \n";
  printf "MAIKYSOFT MAIKYSOFT MAIKYSOFT MAIKYSOFT MAIKYSOFT MAIKYSOFT MAIKYSOFT MAIKYSOFT MAIKYSOFT  \n";
  printf "MAIKYSOFT MAIKYSOFT MAIKYSOFT MAIKYSOFT MAIKYSOFT MAIKYSOFT MAIKYSOFT MAIKYSOFT MAIKYSOFT  \n";
  printf "MAIKYSOFT MAIKYSOFT MAIKYSOFT MAIKYSOFT MAIKYSOFT MAIKYSOFT MAIKYSOFT MAIKYSOFT MAIKYSOFT  \n";
  printf "MAIKYSOFT MAIKYSOFT MAIKYSOFT MAIKYSOFT MAIKYSOFT MAIKYSOFT MAIKYSOFT MAIKYSOFT MAIKYSOFT  \n";
  
  printf "${NC}";

  printf "\n"
}
